version: '3.4'

services:
  movieapp.api:
    image: ${DOCKER_REGISTRY-}movieappapi
    build:
      context: .
      dockerfile: MovieApp.Api/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql1
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=<YourStrong@Passw0rd>